services:
  backend:
    image: mindtrace-backend-dev        # tag local para DEV
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    pull_policy: never                  # n√£o puxa do registry
    container_name: mindtrace-backend-dev
    working_dir: /app
    volumes:
      - ./backend:/app
      - /app/pkg/mod
    environment:
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_DB=${POSTGRES_DB}
      - JWT_SECRET=${JWT_SECRET}
      - DB_DRIVER=${DB_DRIVER}
      - GO_ENV=${GO_ENV}
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    image: mindtrace-frontend-dev       # tag local para DEV
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    pull_policy: never
    container_name: mindtrace-frontend-dev
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}
    ports:
      - "5173:5173"
    depends_on:
      - backend
