services:
  db:
    image: postgres:17-alpine
    container_name: mindtrace-db
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - go-mailpit-network
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -h localhost -p 5432 -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s
    tty: true
  mailpit:
    image: axllent/mailpit:latest
    restart: unless-stopped
    ports:
      - "8025:8025" # Web UI
      - "1025:1025" # SMTP server
    networks:
      - go-mailpit-network
  backend:
    image: mindtrace-backend-dev
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    pull_policy: never
    container_name: mindtrace-backend-dev
    working_dir: /app
    volumes:
      - ./backend:/app
      - go-mod-cache:/go/pkg/mod
    env_file:
      - .env
    environment:
      - SMTP_HOST=mailpit
      - SMTP_PORT=1025
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_DB=${POSTGRES_DB}
      - DB_HOST=db
      - DB_PORT=5432
      - JWT_SECRET=${JWT_SECRET}
      - DB_DRIVER=${DB_DRIVER}
      - GO_ENV=${GO_ENV}
      - SKIP_DB_INIT=${SKIP_DB_INIT}
      - FRONTEND_ORIGINS=${FRONTEND_ORIGINS}
    networks:
      - go-mailpit-network
    ports:
      - "9090:9090"
    depends_on:
      db:
        condition: service_healthy
    tty: true
  frontend:
    image: mindtrace-frontend-dev # tag local para DEV
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    pull_policy: never
    container_name: mindtrace-frontend-dev
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - go-mailpit-network
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}
    ports:
      - "5173:5173"
    depends_on:
      - backend
    tty: true

volumes:
  go-mod-cache:
networks:
  go-mailpit-network:
    driver: bridge